Support for list at least for json
ilteoood/flutter_i18n pull request #219
Opened 2024-03-17 05:09 UTC by Judimax

2024-03-17 09:36 UTC, ilteoood commented
Could you add some tests that proved that what you did is correct?

2024-03-17 14:39 UTC, Judimax commented
Greetings I have made the edits as requested I updated the android/app/build.gradle to version 34 to get the andrioid integrations test to pass not sure how that fares with backwards comptability

2024-03-17 23:48 UTC, Judimax commented
the changes
* [UPDATE] Updated _decodeFromMap in simple_translator.dart to handle subMap as a dynamic type, reintroducing checks and handling for subMap being a List.
* [UPDATE] Modified calculateSubmap in simple_translator.dart to return a dynamic type and reintroduced logic to handle the decodedSubMap as either Map or List, including handling list indexing and nested data structures.

2024-03-18 21:32 UTC, ilteoood requested changes

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +      final result = subMap[int.parse(lastKeyPart)] is String
subMap[int.parse(lastKeyPart)] is calculated multiple times. Extract its value in a variable

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +      if (int.parse(lastKeyPart) >= subMap.length) {
int.parse(lastKeyPart) is done multiple times. extract the result in a variable

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +      final String lastKeyPart = key.split(this.keySeparator!).last;
lastKeyPart is calculated in the exact same way for both list and map. extract its value outside the if statement.

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +    final dynamic subMap = calculateSubmap(key);
As it's not only a map anymore, the name `subMap` is not correct anymore

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +        if(int.parse(listKey) < decodedSubMap.length){
int parse repeated multiple times. extract it.

2024-03-18 21:32 UTC, ilteoood commented on lib/utils/simple_translator.dart
> +      } else if( decodedSubMap is Map) {
```suggestion
      } else if (decodedSubMap is Map) {
```

2024-03-19 01:34 UTC, Judimax commented
I appreciate the lazer focus on best coding practices I haven't seen devotion like that in my day to day so I had to dumb it back

2024-03-28 22:49 UTC, Judimax commented
Checking in any updates

2024-04-28 11:16 UTC, ilteoood commented
Hi @Judimax, sorry for being late in the review process.

I don't think that this PR is something that should be merged atm: it complicates the implementation and what you want desire can be achieved using a syntax like:
```
  'key': {
    '0': 'value'
    ...
  }
```

2024-06-11 18:40 UTC, closed without merging